name: Bug Report
description: Report a bug with create-software-factory
labels: ["bug"]
body:
  - type: input
    id: version
    attributes:
      label: Version
      description: "Run `npx create-software-factory --version`"
      placeholder: "0.1.0"
    validations:
      required: true
  - type: input
    id: node-version
    attributes:
      label: Node.js version
      description: "Run `node --version`"
      placeholder: "v20.0.0"
    validations:
      required: true
  - type: dropdown
    id: flow
    attributes:
      label: Which flow?
      options:
        - Interactive create (no --from)
        - GitHub import (--from)
        - Both
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the issue
      value: |
        1. Run `npx create-software-factory ...`
        2. Select ...
        3. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Paste any error output
      render: shell
